# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "F:/KIT/Masterarbeit/Dataset_builder/Blender2.91/",
    "pip": [
      "h5py",
      "scikit-image"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>"
        }
      }
    },
    {
      "module": "loader.BlendLoader",
      "config": {
        "path": "<args:1>",
        "datablocks": ["objects", "lights"],
        "obj_types": ["mesh", "light"]
      }
    },
    {
      "module": "manipulators.WorldManipulator",
      "config": {
        "cf_set_world_category_id": 0  # this sets the worlds background category id to 0
      }
    },
    # {
    #   "module": "lighting.LightLoader",
    #   "config": {
    #     "lights": [
    #       {
    #         "type": "POINT",
    #         "location": [100, -7, 0.4],
    #         "rotation": [3.142, 1.57, 1.57],
    #         "energy": 1
    #       }
    #     ]
    #   }
    # },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation/value",
        "intrinsics": {
          "fov": 1,
          "resolution_x": 1280,             #960,
          "resolution_y": 960             #1280
        }
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "render_normals": True,
        "normals_output_key": "normals",
        "render_distance": True,
        "distance_output_key": "distance"
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": ["class", "instance", "name"]
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "distance": [
          {"module": "postprocessing.TrimRedundantChannels"},
          {"module": "postprocessing.Dist2Depth"}
          ]
        }
      }
    }
  ]
}
